pretrained_base_model_path: "./pretrained_weights/sd-image-variations-diffusers"
pretrained_vae_path: "./pretrained_weights/sd-vae-ft-mse"

denoising_unet_path: './pretrained_weights/EchoMimicV2/denoising_unet.pth'
reference_unet_path: "./pretrained_weights/EchoMimicV2/reference_unet.pth"
pose_encoder_path: "./pretrained_weights/EchoMimicV2/pose_encoder.pth"
motion_module_path: './pretrained_weights/EchoMimicV2/motion_module.pth'

audio_mapper_path: "./pretrained_weights/audio_mapper-50000.pth"
auido_guider_path: "./pretrained_weights/wav2vec2-base-960h"
auto_flow_path: "./pretrained_weights/AutoFlow"
audio_model_path: "./pretrained_weights/audio_processor/tiny.pt"
inference_config: "/workspace/configs/inference/inference_v2.yaml"
weight_dtype: 'fp16'

# 默认参数设置
default_params:
  width: 512
  height: 512
  steps: 4
  guidance_scale: 1.0
  fps: 24
  seed: 420
  length: 100
  context_frames: 12
  context_overlap: 3
  sample_rate: 16000 