# -----------------  EchoMimic V2 • Accelerated Config  -----------------

pretrained_base_model_path: "./pretrained_weights/sd-image-variations-diffusers"
pretrained_vae_path:        "./pretrained_weights/sd-vae-ft-mse"

# —— 加速版权重 ——
denoising_unet_path:   "./pretrained_weights/EchoMimicV2/denoising_unet_acc.pth"
reference_unet_path:   "./pretrained_weights/EchoMimicV2/reference_unet.pth"
pose_encoder_path:     "./pretrained_weights/EchoMimicV2/pose_encoder.pth"          # 仍沿用原版
motion_module_path:    "./pretrained_weights/EchoMimicV2/motion_module_acc.pth"

# —— 语音 & Flow 模型 ——
audio_mapper_path: "./pretrained_weights/audio_mapper-50000.pth"
auido_guider_path: "./pretrained_weights/wav2vec2-base-960h"
auto_flow_path:   "./pretrained_weights/AutoFlow"
audio_model_path: "./pretrained_weights/audio_processor/tiny.pt"

# —— 推理配置 （配合加速脚本）——
inference_config: "/workspace/configs/inference/inference_v2.yaml"

# —— 精度 / 调度器 ——
weight_dtype: 'fp16'
sampler: 'LCM'                     # 让脚本自动替换为 LCMScheduler

# -----------------  默认推理参数  -----------------
default_params:
  width: 512
  height: 512
  steps: 8                         # LCM 推荐 ≤8
  guidance_scale: 1.0
  fps: 24
  seed: 420
  length: 72                       # 3 秒 @ 24 fps
  context_frames: 6
  context_overlap: 2
  sample_rate: 16000
